export interface Flat {
  id: string;
  city: string;
  price: number;
  squareMeters: number;
  distanceFromCenter: number;
  furnished: boolean;
  rooms: number;
  floor: number;
  totalFloors: number;
  hasElevator: boolean;
  amenities: string[];
  description: string;
  address: string;
}

export const mockFlats: Flat[] = [
  {
    id: "pg-001",
    city: "Podgorica",
    price: 165000,
    squareMeters: 75,
    distanceFromCenter: 1.2,
    furnished: true,
    rooms: 3,
    floor: 4,
    totalFloors: 6,
    hasElevator: true,
    amenities: ["balcony", "parking", "air conditioning", "storage"],
    description: "Modern apartment in City Kvart, recently renovated with high-end finishes",
    address: "City Kvart, Podgorica"
  },
  {
    id: "pg-002",
    city: "Podgorica",
    price: 89000,
    squareMeters: 45,
    distanceFromCenter: 2.5,
    furnished: false,
    rooms: 2,
    floor: 2,
    totalFloors: 4,
    hasElevator: false,
    amenities: ["balcony", "storage"],
    description: "Cozy apartment in Zabjelo, perfect for small families",
    address: "Zabjelo, Kralja Nikole"
  },
  {
    id: "nk-001",
    city: "Niksic",
    price: 78000,
    squareMeters: 65,
    distanceFromCenter: 0.8,
    furnished: true,
    rooms: 2,
    floor: 3,
    totalFloors: 5,
    hasElevator: true,
    amenities: ["parking", "air conditioning"],
    description: "Central location with great views of the city",
    address: "Njegoševa ulica"
  },
  {
    id: "bd-001",
    city: "Budva",
    price: 250000,
    squareMeters: 60,
    distanceFromCenter: 0.3,
    furnished: true,
    rooms: 2,
    floor: 6,
    totalFloors: 7,
    hasElevator: true,
    amenities: ["sea view", "balcony", "parking", "air conditioning", "pool"],
    description: "Luxury apartment with sea view, walking distance to the beach",
    address: "TQ Plaza vicinity"
  },
  {
    id: "tg-001",
    city: "Tivat",
    price: 195000,
    squareMeters: 55,
    distanceFromCenter: 1.5,
    furnished: true,
    rooms: 2,
    floor: 2,
    totalFloors: 4,
    hasElevator: true,
    amenities: ["sea view", "balcony", "parking", "air conditioning"],
    description: "Modern apartment near Porto Montenegro",
    address: "Seljanovo"
  },
  {
    id: "pg-003",
    city: "Podgorica",
    price: 145000,
    squareMeters: 85,
    distanceFromCenter: 3.1,
    furnished: false,
    rooms: 4,
    floor: 1,
    totalFloors: 3,
    hasElevator: false,
    amenities: ["garden", "parking", "storage"],
    description: "Spacious ground floor apartment with private garden in Tološi",
    address: "Tološi, Partizanski put"
  },
  {
    id: "br-001",
    city: "Bar",
    price: 120000,
    squareMeters: 70,
    distanceFromCenter: 1.0,
    furnished: true,
    rooms: 3,
    floor: 4,
    totalFloors: 5,
    hasElevator: true,
    amenities: ["sea view", "balcony", "parking"],
    description: "Well-maintained apartment with partial sea view",
    address: "Topolica II"
  },
  {
    id: "nk-002",
    city: "Niksic",
    price: 65000,
    squareMeters: 55,
    distanceFromCenter: 1.5,
    furnished: false,
    rooms: 2,
    floor: 1,
    totalFloors: 3,
    hasElevator: false,
    amenities: ["parking", "storage"],
    description: "Affordable apartment in quiet neighborhood",
    address: "Dragova Luka"
  },
  {
    id: "pg-004",
    city: "Podgorica",
    price: 110000,
    squareMeters: 60,
    distanceFromCenter: 2.8,
    furnished: true,
    rooms: 2,
    floor: 3,
    totalFloors: 5,
    hasElevator: true,
    amenities: ["balcony", "air conditioning", "parking"],
    description: "Comfortable apartment in a quiet neighborhood, ideal for families",
    address: "Blok VI, Podgorica"
  },
  {
    id: "pg-005",
    city: "Podgorica",
    price: 175000,
    squareMeters: 80,
    distanceFromCenter: 1.0,
    furnished: true,
    rooms: 3,
    floor: 5,
    totalFloors: 7,
    hasElevator: true,
    amenities: ["balcony", "parking", "storage", "air conditioning"],
    description: "Spacious and modern apartment near Delta City",
    address: "Preko Morače, Podgorica"
  },
  {
    id: "bd-002",
    city: "Budva",
    price: 320000,
    squareMeters: 75,
    distanceFromCenter: 0.5,
    furnished: true,
    rooms: 3,
    floor: 6,
    totalFloors: 8,
    hasElevator: true,
    amenities: ["sea view", "balcony", "parking", "pool", "air conditioning"],
    description: "Luxury penthouse with a breathtaking sea view",
    address: "Rafailovići, Budva"
  },
  {
    id: "bd-003",
    city: "Budva",
    price: 190000,
    squareMeters: 55,
    distanceFromCenter: 1.2,
    furnished: false,
    rooms: 2,
    floor: 3,
    totalFloors: 5,
    hasElevator: true,
    amenities: ["balcony", "parking"],
    description: "Newly built apartment, excellent investment opportunity",
    address: "Rozino, Budva"
  },
  {
    id: "tg-002",
    city: "Tivat",
    price: 270000,
    squareMeters: 65,
    distanceFromCenter: 0.7,
    furnished: true,
    rooms: 3,
    floor: 4,
    totalFloors: 6,
    hasElevator: true,
    amenities: ["sea view", "balcony", "parking", "storage", "air conditioning"],
    description: "High-end apartment with panoramic sea views",
    address: "Porto Montenegro, Tivat"
  },
  {
    id: "nk-003",
    city: "Niksic",
    price: 72000,
    squareMeters: 60,
    distanceFromCenter: 1.3,
    furnished: false,
    rooms: 2,
    floor: 2,
    totalFloors: 4,
    hasElevator: false,
    amenities: ["parking"],
    description: "Affordable apartment, great value for money",
    address: "Kličevac, Niksic"
  },
  {
    id: "br-002",
    city: "Bar",
    price: 135000,
    squareMeters: 75,
    distanceFromCenter: 0.8,
    furnished: true,
    rooms: 3,
    floor: 5,
    totalFloors: 6,
    hasElevator: true,
    amenities: ["sea view", "balcony", "parking", "air conditioning"],
    description: "Spacious apartment with a fantastic view of the Adriatic Sea",
    address: "Šušanj, Bar"
  },
  {
    id: "br-003",
    city: "Bar",
    price: 95000,
    squareMeters: 50,
    distanceFromCenter: 1.5,
    furnished: false,
    rooms: 2,
    floor: 2,
    totalFloors: 4,
    hasElevator: false,
    amenities: ["balcony", "parking"],
    description: "Cozy apartment in a quiet location",
    address: "Polje, Bar"
  },
  {
    id: "ul-001",
    city: "Ulcinj",
    price: 210000,
    squareMeters: 85,
    distanceFromCenter: 0.6,
    furnished: true,
    rooms: 3,
    floor: 6,
    totalFloors: 8,
    hasElevator: true,
    amenities: ["sea view", "balcony", "parking", "air conditioning", "storage"],
    description: "Spacious modern apartment with an amazing sea view",
    address: "Velika Plaža, Ulcinj"
  },
  {
    id: "ul-002",
    city: "Ulcinj",
    price: 160000,
    squareMeters: 70,
    distanceFromCenter: 1.0,
    furnished: true,
    rooms: 3,
    floor: 4,
    totalFloors: 6,
    hasElevator: true,
    amenities: ["balcony", "parking", "air conditioning"],
    description: "Modern apartment near the famous Long Beach",
    address: "Kodre, Ulcinj"
  }
];